language: python
python: '2.7'
notifications:
  email:
    recipients:
    - twodopeshaggy@gmail.com
    on_success: change
    on_failure: always
install:
- npm install -g csslint
- npm install -g try-thread-sleep
- gem install mdl
- pip install markdown
- pip install feedparser
- pip install beautifulsoup4
- pip install requests
- pip install flake8
script:
- flake8
- csslint --ignore=ids,box-model input/style.css
- mdl -s mdl-rules.rb .
- make
- "./link_validator.py output/"
after_success:
- "./deploy.sh"
env:
  global:
  - secure: dPpRhxBV4eLu0fN0KNcHD+b30AFsFpaftexnlWF8nh29C13Ii77jAvt12uuV/zX77nFcZdsL1lrYxPNuI7ZJy6ail97R5u6Hh12ZCpmyVCrd47AAYO+7XAGZjR/bVu+mEY+w5AS2ZjJGXIzBcCjRnTFUWoaXXxCXBI2yfIZyV0+fnAS8j4uJDz0mzUdWGjvdPeys5uEbJW6kLLvJRKAa0wv6VEIqTmICkIEc7WYNuqb4P7nKbNzcd7EgEKOcN9EhRDpzmo4Nb0zmmDA+OmNkP8nWT9X8lKlfR7xQMPSZTQz4uUmGVb/tlPM7Rbq0R+/rWXigNka5u/lhgiPBja2vhwGl17EAtQZ+jAXTPF8xbC8sXKF+Y9Awixx10AZgNilUp8ica2RFHYQ9H/KTR1jJTgZeojFMrkM/jUAsLpk4PdpsyjqC5GShkM3+9rkADzD/veZ/nX65jMJ5L4B6SslRd8q9BlbDenWhf+Jbn5NhaNXkLPhFj3kCifKILM08LXyVuMnpn7RVDt+xf5WeEaglNAkdeyGHbhBIVV0SYa1amH1ZpjG2445PYpZAdFHzuowLGtrkBq6z8kwK7idIsdKvEeyVOk35/Pidatbo+fogkAHaATjYtHStylOgVFrXEBR3eHUrirfNlf+EzP1L2ihDJiErQnQUYbPnxQD/h4BE+1w=
