"Resources"
{
	"materials/hud/leaderboard_class_boss_demoexcavation.vmt"	"file"
	"materials/hud/leaderboard_class_boss_demoexcavation.vtf"	"file"
	"materials/hud/leaderboard_class_boss_demoexcavation_giant.vmt"	"file"
	"materials/hud/leaderboard_class_boss_soldierexcavation.vmt"	"file"
	"materials/hud/leaderboard_class_boss_soldierexcavation.vtf"	"file"
	"materials/hud/leaderboard_class_boss_soldierexcavation_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_caber.vmt"	"file"
	"materials/hud/leaderboard_class_demo_caber.vtf"	"file"
	"materials/hud/leaderboard_class_demo_caber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_demo_rapidcaber.vmt"	"file"
	"materials/hud/leaderboard_class_demo_rapidcaber.vtf"	"file"
	"materials/hud/leaderboard_class_demo_rapidcaber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_booster.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_booster.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_booster_giant.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_dwarf.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_dwarf.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_dwarf_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf_giant.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_camper.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_camper.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_camper_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_equalizer_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_escape.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_escape.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_escape_giant.vmt"	"file"
	"materials/hud/leaderboard_class_spy_kunai.vmt"	"file"
	"materials/hud/leaderboard_class_spy_kunai.vtf"	"file"
	"materials/hud/leaderboard_class_spy_kunai_giant.vmt"	"file"
}